name = "cloudflare-freerss"
main = "src/worker.ts"
compatibility_date = "2024-08-21"
minify = true
node_compat = false

[vars]
ADMIN_TOKEN = "changeme"

[[kv_namespaces]]
binding = "FEED_RULES"
id = "your_prod_kv_id"
preview_id = "local_dev_kv_id"